### ISSUE TITLE
Curl doesn't find the download anymore

### ISSUE THREAD

**Issue by larsinka** [5aaee9/homebrew-kicad-nightly#1]
I get this error trying to use homebrew to upgrade kicad-nightly:

`curl: (22) The requested URL returned error: 404                              

Error: Download failed on Cask 'kicad-nightly' with message: Download failed: https://kicad-downloads.s3.cern.ch/osx/nightly/kicad-unified-universal-20230203-0236.dmg`

**Comment by larsinka** [comment]
Since I don't know how GitHub works I fixed this in a fork .. idk, can you like merge it together?

**Comment by 5aaee9** [comment]
It should been fixed after ada739025a242e4e00042c1509d26f20c192b887
